In [1]:
import numpy as np
import sys

In [7]:
# Create an array
a = np.array([1,2,3]) # 1d
b = np.array([[1,2,3], [3,4,5]]) # 2d (2 lists within a list)
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [3, 4, 5]]))

In [8]:
# Get dimension
b.ndim

2

In [10]:
# Get shape (rows and columns)
b.shape

(2, 3)

In [11]:
# Get type
b.dtype

dtype('int32')

In [12]:
# Get the number of bytes used
b.itemsize

4

In [13]:
# Get total size
b.nbytes

24

### Accessing/ Changing specific elements, rows, columns, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
# Get a specific element [row, col]
a[1, 5]

13

In [21]:
# Get a specific row
a[0, :] # Or a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [23]:
# Using slicing to access elements
a[0, 1:6:2]

array([2, 4, 6])

In [24]:
# Change values
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

### Shortcuts for different arrays 

In [27]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# All 1s
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [30]:
# Any other number
np.full((2,3), 6) # Args - Dimension and number to fill

array([[6, 6, 6],
       [6, 6, 6]])

In [32]:
# Any other number with the dimension of a previously created array
np.full_like(a, 6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [35]:
# Array with random decimals
np.random.rand(2,3)

array([[0.55584307, 0.79161701, 0.30874616],
       [0.85357395, 0.4316693 , 0.47271658]])

In [36]:
# Array with random decimals with the dimension of a previously created array
np.random.random_sample(a.shape)

array([[0.30712755, 0.26755864, 0.94344666, 0.5362249 , 0.64764156,
        0.49289932, 0.1724776 ],
       [0.93718228, 0.60847374, 0.21519234, 0.34951192, 0.11234311,
        0.56596562, 0.7759535 ]])

In [39]:
# Array with random decimal values
np.random.randint(1, 7, size=(2,3)) # Start, end (both inclusive), array_size

array([[3, 2, 1],
       [6, 2, 5]])

In [41]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
# Repeat the contents of an array and append
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r2 = np.repeat(arr, 3, axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


### Problem 1

In [56]:
n1 = np.ones((5, 5))
n1[1:4, 1:4] = 0
n1[2,2] = 9
n1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
# Copying an array
a = np.array([1,2,3])
b = a.copy()
b
# If you type b=a, changing b will change a as well

array([1, 2, 3])

### MATHEMATICS

In [63]:
# Element wise operations

a + 2

array([3, 4, 5])

In [61]:
a / 2

array([0.5, 1. , 1.5])

In [62]:
a + b

array([2, 4, 6])

In [64]:
a ** 2

array([1, 4, 9])

In [65]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

##### DOCUMENTATION --> https://docs.scipy.org/doc/numpy/reference/routines.math.html

### LINEAR ALGEBRA

In [67]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

In [70]:
# Matrix Multiplication
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [73]:
# Determinant of a matrix
a = np.identity(3)
np.linalg.det(a)

1.0

##### DOCUMENTATION --> https://numpy.org/doc/stable/reference/routines.linalg.html

### STATISTICS

In [74]:
stats = np.array([[1,2,3],[4,5,6]])

In [75]:
# Minimum
np.min(stats)

1

In [76]:
# Maximum
np.max(stats)

6

In [79]:
# Sum
print(np.sum(stats))
print(np.sum(stats, axis=0)) # Sum of both rows

21
[5 7 9]


### REORGANIZING ARRAYS

In [81]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [85]:
# Change the shape of a matrix
# To use reshape, make sure the resulting matrix has the same number of elements as the base matrix
print(a.reshape((8,1)))
print()
print(a.reshape(4,2))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [87]:
# Vertical stacks
# Dimension is important here as well

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))
print()
print(np.vstack([v1,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [89]:
# Horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))
print()
print(np.hstack((h1,h2,h1)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]

[[1. 1. 1. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 0. 1. 1. 1. 1.]]


### LOADING DATA FROM FILE

In [92]:
a = np.genfromtxt('data.txt', delimiter=',') # Delimiter = Separator
a

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [93]:
a.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

 ### BOOLEAN MASKING AND ADVANCED INDEXING

In [96]:
a > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [95]:
a[a > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [101]:
a = np.array([1,2,3,4,5])
a[[0,1,2]] # Returns the first 3 elements

array([1, 2, 3])

In [103]:
(a > 1) & (a < 4)

array([False,  True,  True, False, False])

In [104]:
~((a > 1) & (a < 4)) # Complement

array([ True, False, False,  True,  True])